(source gnu)
(source melpa)

;; auto-complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")

;; editing utilities
(depends-on "expand-region")
(depends-on "wrap-region")
(depends-on "undo-tree")
(depends-on "multiple-cursors")
(depends-on "smartrep")
(depends-on "yasnippet")
(depends-on "goto-chg")
(depends-on "smartparens")
(depends-on "ag")
(depends-on "highlight-symbol")

;; buffer utils
(depends-on "elscreen")
(depends-on "yascroll")

;;flymake
(depends-on "flycheck")

(depends-on "coffee-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "less-css-mode")
(depends-on "haml-mode")
(depends-on "jade-mode")
(depends-on "go-mode")
(depends-on "php-mode")
(depends-on "rvm")
(depends-on "ruby-block")
(depends-on "ruby-tools")
(depends-on "dockerfile-mode")
(depends-on "rspec-simple" :git "https://github.com/code-mancers/rspec-simple.git" :files ("*"))

;;;; markup language
(depends-on "htmlize")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "emmet-mode")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "textile-mode")
(depends-on "pandoc-mode")

;; emacs-lisp
(depends-on "elisp-slime-nav")
(depends-on "thingopt")

;; common utility
(depends-on "quickrun")

;; helm
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-projectile")

;; VCS
(depends-on "magit")
(depends-on "git-gutter")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")

;; directory operation
(depends-on "direx")
(depends-on "pkg-info")
(depends-on "projectile")

;; basic
(depends-on "init-loader")
(depends-on "solarized-theme")
(depends-on "zenburn-theme")
(depends-on "moe-theme")
(depends-on "exec-path-from-shell")
(depends-on "anzu")
(depends-on "redo+")
(depends-on "dash-at-point")
(depends-on "powerline")

